### ISSUE TITLE
Plugin System Environment: Add Command Line Parameters

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/inexor-rgf-application#35]
### Tasks

- [ ] Create entity instances for each command line argument
- [ ] Configuration File `config/env.toml`
    ```toml
    enable_cmd_line_args = true
    enable_env_variables = true
    ```

### Resources

* https://doc.rust-lang.org/stable/std/env/fn.args.html
